### ISSUE TITLE
Master Task List

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team5#14]
* Login
- [ ] Log in User 
- [ ] Implement Social Login API

* Logout
- [ ] Log out user

* Sign in
- [ ] Create new user

* Browse
- [ ] Load outfits from Database
- [ ] Route to other components

* Upload
- [ ]  Photo upload from filesystem
- [ ] Make API call for component classification
- [ ] Map DeepFashion classes to our system
- [ ] Outfit tagging interface
- [ ] Upload item to database
- [ ] Log satisfaction data

* Calendar 
- [ ] Component interface design
- [ ] Route to detail component

* Search
- [ ] Component interface design
- [ ] Autocomplete search query
- [ ] Search item by tag
- [ ] Search outfit by item

* OutfitDetail
- [ ] Load information from database
- [ ] Component interface design

* OutfitEdit
- [ ] Edit mode interface
- [ ] Edit item/tag for all outfits
- [ ] Edit item/tag only for current outfit
