### ISSUE TITLE
[Sprint3] Task List

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team5#15]
### Browse 
Assignee: @iamsungyeonjoo 
- [x] Implement basic Redux skeleton
- [x] Load outfits from Database - implement outfit reducers(getting whole list, setting selected outfit)
- [x] Route to other components - Calendar, Outfitdetail
- [x] Add AddItem component(skeleton code) - work as connection to Upload process
- [ ] Implement testing

### Upload 
Assignee: @ttoru96 @haesookim @iamsungyeonjoo 
- [ ]  Photo upload from filesystem
- [ ] Make API call for component classification
- [ ] Map DeepFashion classes to our system
- [ ] Outfit tagging interface
- [ ] Upload item to database
- [ ] Log satisfaction data

### Search 
Assignee: @haesookim @ttoru96 @dreammerkr 
- [ ] Component interface design
- [ ] Autocomplete search query
- [ ] Search item by tag
- [ ] Search outfit by item

## Research & Development Tasks
- [ ] Explore DeepFashion API & Document
- [ ] Establish Database relations
  * User - Outfit relations
  * Outfit - Item relations
  * Item - Tag relations
- [ ] Define Store & Reducers & Action functionalities 
- [x] Integrate Travis CI settings @ttoru96
